# 下面两行是指明依赖库的来源地址
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

# 忽略引入库的所有警告（强迫症者的福音啊）
inhibit_all_warnings!

# 针对MyApp target引入AFNetworking
# 针对MyAppTests target引入OCMock，
target 'KaiDemo' do

  # pod 'AFNetworking', '~> 3.0'

  pod 'LookinServer', :configurations => ['Debug']


  # target 'MyAppTests' do
  #   inherit! :search_paths
  #   pod 'OCMock', '~> 2.0.1'
  # end
end

# # 这个是cocoapods的一些配置,官网并没有太详细的说明,一般采取默认就好了,也就是不写.
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     puts target.name
#   end
# end